import type { CSSProperties } from "react";

export const S: Record<string, CSSProperties> = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#0F172A",
    color: "#E2E8F0",
    fontFamily: "'Noto Sans JP','Helvetica Neue',sans-serif",
    maxWidth: 480,
    margin: "0 auto",
    padding: "0 0 80px 0",
    position: "relative",
    overflowX: "hidden",
  },
  startScreen: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    minHeight: "100vh",
    padding: "32px 18px",
  },
  title: {
    fontSize: 26,
    fontWeight: 800,
    letterSpacing: 6,
    margin: 0,
    background: "linear-gradient(135deg,#F59E0B,#3B82F6)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  },
  modeCard: {
    padding: "14px 16px",
    backgroundColor: "#1E293B",
    borderRadius: 10,
    cursor: "pointer",
    transition: "all 0.15s",
  },
  primaryButton: {
    padding: "10px 26px",
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 2,
    color: "#0F172A",
    background: "linear-gradient(135deg,#F59E0B,#FBBF24)",
    border: "none",
    borderRadius: 6,
    cursor: "pointer",
  },
  secondaryButton: {
    padding: "10px 16px",
    fontSize: 12,
    fontWeight: 600,
    color: "#94A3B8",
    background: "none",
    border: "1px solid #334155",
    borderRadius: 6,
    cursor: "pointer",
  },
  narrativeBox: {
    padding: "12px",
    backgroundColor: "#1E293B",
    borderRadius: 8,
    borderLeft: "3px solid",
  },
  narrativeTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "#E2E8F0",
    margin: "0 0 8px",
  },
  backButton: {
    background: "none",
    border: "1px solid #334155",
    color: "#94A3B8",
    borderRadius: 5,
    padding: "4px 10px",
    fontSize: 10,
    cursor: "pointer",
  },
};
